replicaCount: 1

image:
  repository: registry
  tag: 2.8.1
  pullPolicy: Always

service:
  name: registry
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: nginx
  path: /
  hosts:
    - registry.cdnsistemas.local

