expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    className: "nginx"
    hosts:
      core: registry.cdnsistemas.local
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"

externalURL: "http://registry.cdnsistemas.local:80"

portal:
  image:
    repository: goharbor/harbor-portal
    tag: v2.13.0

core:
  image:
    repository: goharbor/harbor-core
    tag: v2.13.0

jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: v2.13.0

registry:
  registry:
    image:
      repository: goharbor/registry-photon
      tag: v2.13.0
  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: v2.13.0

trivy:
  enabled: true
  image:
    repository: goharbor/trivy-adapter-photon
    tag: v2.13.0

database:
  type: internal
  internal:
    image:
      repository: goharbor/harbor-db
      tag: v2.13.0

redis:
  type: internal
  internal:
    image:
      repository: goharbor/redis-photon
      tag: v2.13.0

exporter:
  image:
    repository: goharbor/harbor-exporter
    tag: v2.13.0

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      jobLog:
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: 1Gi
    database:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 1Gi
    redis:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 1Gi
    trivy:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 1Gi
  imageChartStorage:
    disableredirect: false
    type: filesystem
    filesystem:
      rootdirectory: /storage

existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
harborAdminPassword: "Harbor12345"

logLevel: debug